#!/usr/bin/env python3
"""Full two-way population: make the calendar and the vault complete mirror images (operator-approved
2026-09-18, event dh29hru0psba2f8pbsglcpepng).

Contract: same text on both sides; the vault alone has a place to hang the picture. Charts are the one
per-layer exception where the VAULT is the source (its notes carry the data-form chart blocks): the
calendar's chart notes are deleted and the vault's promoted up. Every other layer: calendar is the source.
Every note gets an identity key (tools/links.py) as it is adopted; links go up name+key, down plain.

  populate.py [--apply]     (dry run by default; prints the plan and counts)
"""
import argparse, hashlib, re, sys
from collections import Counter
from pathlib import Path

CC = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(CC)); sys.path.insert(0, str(CC / "tools"))
import comms_poller as cp  # noqa: E402
import links  # noqa: E402
import mirror  # noqa: E402
import keys as K  # noqa: E402

CHART_LAYERS = {"3002": ("HD", "Human Design"), "3003": ("AST", "Astrology"),
                "3004": ("BAZI", "BaZi"), "3005": ("GK", "Gene Keys")}
FOLDERS = {"3000-01-01": "Seed", "3000-01-02": "Indexes", "3001": "People", "3008": "Puddle", "3009": "Puddle",
           "3010": "Garden", "3020": "Records", "3030": "Architecture", "3040": "Rapport"}
TERRITORY = "Calendar mirror"
CFG = {}     # filled by main for band_floor
SKYRIVER = "Skyriver/Charts"


def layer_folder(day: str) -> str:
    if day in FOLDERS:
        return FOLDERS[day]
    if day[:4] in FOLDERS:
        return FOLDERS[day[:4]]
    if int(day[:4]) >= 8000:
        return "Transcripts"
    return f"Other/{day}"


def event_day(ev) -> str:
    return ev["start"].get("date") or ev["start"]["dateTime"][:10]


def list_all(svc, cal):
    items, page = [], None
    while True:
        r = svc.events().list(calendarId=cal, timeMin=mirror.band_floor(CFG), timeMax="9999-01-01T00:00:00Z",
                              singleEvents=True, maxResults=2500, pageToken=page).execute()
        items += r.get("items", []); page = r.get("nextPageToken")
        if not page:
            return items


def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def vault_people(vault: Path):
    """(codename, given, {chart kind: path}) for every person folder holding a record note."""
    out = []
    for folder in sorted((vault / SKYRIVER).iterdir()):
        if not folder.is_dir():
            continue
        rec = next((p for p in folder.glob("*.md") if re.search(r"^Name:", p.read_text(), re.M)), None)
        if not rec:
            continue
        text = rec.read_text()
        name = re.search(r"^Name:\s*(.+)$", text, re.M).group(1).strip()
        date = re.search(r"^Date:\s*(\d{4})-(\d\d)-(\d\d)", text, re.M)
        if not date:
            continue
        code = f"{slugify(name)}-{''.join(date.groups())}"
        given = name.split()[0].title()
        charts = {}
        for layer, (prefix, kind) in CHART_LAYERS.items():
            p = folder / f"{given} - {kind}.md"
            if p.exists():
                charts[layer] = p
        out.append((code, given, charts))
    return out


def chart_key_line(text: str, key: str) -> str:
    """Chart notes are regenerated by the watcher, which keeps only what sits below the first ---
    divider: the key must live there to survive."""
    if links.key_of(text) == key:
        return text
    if "\n---\n" not in text:
        return text.rstrip() + "\n\n---\n" + key + "\n"
    return text.rstrip() + "\n" + key + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--config", default=str(CC / "comms.toml"))
    a = ap.parse_args()
    dry = not a.apply
    cfg = cp.load_config(Path(a.config)); svc = cp.get_service(cfg); cal = cfg["calendar_id"]
    CFG.update(cfg)
    vault = Path(cfg["mirror_dir"]).expanduser()
    class_keys = set(K.load(cfg).values())

    events = [e for e in list_all(svc, cal) if re.match(r"^Note:?\s", e.get("summary", ""))]
    taken = set(class_keys)
    for e in events:
        for tok in (e.get("location") or "").split():
            taken.add(tok)
        k = links.key_of(e.get("description") or "")
        if k:
            taken.add(k)
    for p in vault.rglob("*.md"):
        k = links.key_of(p.read_text(encoding="utf-8"))
        if k:
            taken.add(k)

    counts = Counter(); minted = 0
    plan_del, plan_up, plan_down = [], [], []

    # ---- charts: vault -> calendar -----------------------------------------------------------
    for e in events:
        if event_day(e)[:4] in CHART_LAYERS:
            plan_del.append(e)
    people = vault_people(vault)
    for code, given, charts in people:
        for layer, path in charts.items():
            prefix, kind = CHART_LAYERS[layer]
            plan_up.append((f"Note: {prefix} · {code}", f"{layer}-01-01", path))

    # ---- everything else: calendar -> vault ---------------------------------------------------
    existing_by_title = {}
    for e in events:
        day = event_day(e)
        if day[:4] in CHART_LAYERS:
            continue
        priv = e.get("extendedProperties", {}).get("private", {})
        rel = priv.get("mirror_path") or f"{TERRITORY}/{layer_folder(day)}/{mirror.file_name(e['summary'])}"
        if rel in existing_by_title:
            rel = rel[:-3] + f" · {e['id'][:6]}.md"     # same title twice in one layer: keep both, distinct files
        existing_by_title[rel] = e
        plan_down.append((e, rel))

    print(f"plan: delete {len(plan_del)} calendar chart notes; promote {len(plan_up)} vault charts up; "
          f"mirror {len(plan_down)} calendar notes down ({sum(1 for e,_ in plan_down if e.get('extendedProperties',{}).get('private',{}).get('mirror_path'))} already mirrored)")
    print("people in vault:", len(people), "· codenames not on the calendar before:",
          sorted({c for c, _, _ in people} - {re.sub(r'^Note: \w+ · ', '', e['summary']) for e in plan_del}))
    if dry:
        by_day = Counter(event_day(e) for e in plan_del); print("deletes by layer:", dict(by_day))
        print("promotions by layer:", dict(Counter(d for _, d, _ in plan_up)))
        print("down by folder:", dict(Counter(Path(r).parts[1] for _, r in plan_down)))
        return

    # ---- apply --------------------------------------------------------------------------------
    # 1. keys + files first (vault side), so the registry is complete before any calendar write.
    key_for = {}
    for e, rel in plan_down:
        text = e.get("description") or ""
        key = links.key_of(text)
        if not key:
            loc = [t for t in (e.get("location") or "").split() if links.is_key(t) and t not in class_keys]
            key = loc[0] if len(loc) == 1 else links.mint(taken); minted += key not in loc
        key_for[e["id"]] = key
        mirror.REG["name2key"][re.sub(r"^Note:?\s*", "", e["summary"]).strip()] = key
        mirror.REG["name2key"][Path(rel).stem] = key
        mirror.REG["key2name"][key] = re.sub(r"^Note:?\s*", "", e["summary"]).strip()
    for title, day, path in plan_up:
        text = path.read_text(encoding="utf-8")
        key = links.key_of(text) or links.mint(taken)
        key_for[title] = key
        mirror.REG["name2key"][title[6:]] = key; mirror.REG["name2key"][path.stem] = key
        mirror.REG["key2name"][key] = title[6:]

    # 2. delete the calendar's chart notes
    for e in plan_del:
        cp.pace(); svc.events().delete(calendarId=cal, eventId=e["id"]).execute(); counts["deleted"] += 1

    # 3. promote vault charts (key line into the file's tail, then insert the calendar twin)
    for title, day, path in plan_up:
        key = key_for[title]
        raw = path.read_text(encoding="utf-8")
        new = chart_key_line(raw, key)
        if new != raw:
            path.write_text(new, encoding="utf-8"); counts["vault files keyed"] += 1
        canon = mirror.canonical(new)
        up = links.up(canon, mirror.REG["name2key"], mirror.REG["missing"])
        rel = str(path.relative_to(vault))
        try:
            cp.check_cap(up, title)
        except cp.CapExceeded as ex:
            print("SKIP", ex); counts["skipped over cap"] += 1; continue
        body = {"summary": title, "start": {"date": day}, "end": {"date": (date.fromisoformat(day) + timedelta(days=1)).isoformat()}, "location": key, "description": up,
                "extendedProperties": {"private": {"comms_kind": "note", "comms_writer": "mirror",
                                                   "mirror_path": rel, "mirror_hash": mirror.h(canon)}}}
        cp.insert_event(svc, cal, body); counts["promoted up"] += 1

    # 4. calendar notes down: key line on both sides, file written, memory set
    for e, rel in plan_down:
        key = key_for[e["id"]]
        desc = e.get("description") or ""
        keyed = links.with_key(desc, key)
        canon_v = links.down(mirror.canonical(keyed), mirror.REG["key2name"])
        path = vault / rel
        keep = mirror.fences(path.read_text(encoding="utf-8")) if path.exists() else ""
        mirror.write_file(path, canon_v, keep, False); counts["written down"] += 1
        priv = {"mirror_path": rel, "mirror_hash": mirror.h(canon_v)}
        body = {"extendedProperties": {"private": priv}}
        if keyed != desc:
            body["description"] = keyed
        loc = (e.get("location") or "").split()
        if key not in loc:
            body["location"] = " ".join(loc + [key])
        cp.write_event(svc, cal, e["id"], body, existing=e, verify=False); counts["calendar keyed"] += 1

    print("done:", dict(counts), "keys minted:", minted, "· link targets without a key:", len(mirror.REG["missing"]),
          sorted(mirror.REG["missing"])[:40])


if __name__ == "__main__":
    main()
